### ISSUE TITLE
support 'renderInPlace' on g-modal component

### ISSUE THREAD

**Issue by rynam0** [VertekCorp/ember-cli-vtkui#22]
The `g-modal` component template should pass the `renderInPlace` attribute through to `ember-modal-dialog` in order to support multiple app instances rendering modals to their individual root elements.

    {{#modal-dialog renderInPlace=true targetAttachment="center" translucentOverlay=true
       container-class="g-modal-container" close="closeModal"}}
         <div class="g-modal-title">{{title}}</div>
        {{yield}}
    {{/modal-dialog}}

**Comment by franktcurran** [comment]
#23

**Comment by rynam0** [comment]
Closed by #23
